# Generated by Django 5.2.17 on 2026-09-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios_themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portfoliotemplate',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfoliotemplate',
            name='template_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
