# Generated by Django 5.2.17 on 2026-09-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios_themes', '0002_portfoliotemplate_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliotemplate',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='portfoliotemplate',
            name='access_level',
            field=models.CharField(choices=[('free', 'Free'), ('verified', 'Verified Email'), ('premium', 'Premium')], default='free', max_length=20),
        ),
    ]
