# Generated by Django 5.2.17 on 2026-10-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios_themes', '0003_remove_portfoliotemplate_is_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotemplate',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='template_previews/'),
        ),
    ]
