# Generated by Django 5.2.17 on 2026-10-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_alter_portfolio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_previews/'),
        ),
        migrations.AddField(
            model_name='project',
            name='pro_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
